In [2]:
import numpy as np

In [10]:
var = np.arange(20).reshape(5, 4)

In [11]:
var

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [12]:
var.mean()

9.5

In [15]:
var[0, :].mean()

1.5

In [16]:
var.mean(axis=1)

array([ 1.5,  5.5,  9.5, 13.5, 17.5])

In [17]:
var.mean(axis=0)

array([ 8.,  9., 10., 11.])

In [20]:
var[2:4, :3]

array([[ 8,  9, 10],
       [12, 13, 14]])

In [26]:
var.cumsum()

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)

In [27]:
import pandas as pd

In [28]:
df = pd.read_csv('../data/titanic.csv')

In [29]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [33]:
a = np.arange(4,10).reshape(2,3)
np.where(a > 6)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))

In [34]:
a[np.where(a > 6)]

array([7, 8, 9])

In [35]:
a

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
df.iloc[-5:, :3]

PassengerId  Survived  Pclass
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

In [50]:
df.loc[880:, ['Name', 'Ticket', 'Fare']]

Name            Ticket     Fare
880  Shelley, Mrs. William (Imanita Parrish Hall)            230433  26.0000
881                            Markun, Mr. Johann            349257   7.8958
882                  Dahlberg, Miss. Gerda Ulrika              7552  10.5167
883                 Banfield, Mr. Frederick James  C.A./SOTON 34068  10.5000
884                        Sutehall, Mr. Henry Jr   SOTON/OQ 392076   7.0500
885          Rice, Mrs. William (Margaret Norton)            382652  29.1250
886                         Montvila, Rev. Juozas            211536  13.0000
887                  Graham, Miss. Margaret Edith            112053  30.0000
888      Johnston, Miss. Catherine Helen "Carrie"        W./C. 6607  23.4500
889                         Behr, Mr. Karl Howell            111369  30.0000
890                           Dooley, Mr. Patrick            370376   7.7500

In [58]:
# get a random sample of sata
df.sample(100, random_state=1)[:5]

PassengerId  Survived  Pclass  \
862          863         1       1   
223          224         0       3   
84            85         1       2   
680          681         0       3   
535          536         1       2   

                                                  Name     Sex   Age  SibSp  \
862  Swift, Mrs. Frederick Joel (Margaret Welles Ba...  female  48.0      0   
223                               Nenkoff, Mr. Christo    male   NaN      0   
84                                 Ilett, Miss. Bertha  female  17.0      0   
680                                Peters, Miss. Katie  female   NaN      0   
535                             Hart, Miss. Eva Miriam  female   7.0      0   

     Parch        Ticket     Fare Cabin Embarked  
862      0         17466  25.9292   D17        S  
223      0        349234   7.8958   NaN        S  
84       0    SO/C 14885  10.5000   NaN        S  
680      0        330935   8.1375   NaN        Q  
535      2  F.C.C. 13529  26.2500   NaN        S

In [70]:
df[['Survived', 'Pclass', 'Fare']][:10]['Fare']

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
5     8.4583
6    51.8625
7    21.0750
8    11.1333
9    30.0708
Name: Fare, dtype: float64

In [78]:
df[df['Fare'] < 35][['Survived', 'Pclass']]

Survived  Pclass
0           0       3
2           1       3
4           0       3
5           0       3
7           0       3
..        ...     ...
886         0       2
887         1       1
888         0       3
889         1       1
890         0       3

[692 rows x 2 columns]

In [79]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')